import nbformat as nbf
nb = nbf.v4.new_notebook()
nb.cells = [
    nbf.v4.new_markdown_cell("# MedScope AI — Colab Inference and API\n\nRun the backend API server on Google Colab using your trained weights from Google Drive."),
    nbf.v4.new_code_cell("#@title 1. Runtime and configuration\nimport os, sys\nREPO_URL = \"https://github.com/prey801/finalyearproject.git\"\nBRANCH = \"main\"\nPROJECT_DIR = \"/content/finalyearproject\"\nUSE_DRIVE = True\nDRIVE_WEIGHTS_DIR = \"/content/drive/MyDrive/medscope-ai/weights\"\nNGROK_AUTH_TOKEN = \"\" #@param {type:\"string\"}\n"),
    nbf.v4.new_code_cell("#@title 2. Mount Google Drive\nif USE_DRIVE:\n    from google.colab import drive\n    drive.mount('/content/drive')"),
    nbf.v4.new_code_cell("#@title 3. Clone repository\n!git clone --branch \"$BRANCH\" \"$REPO_URL\" \"$PROJECT_DIR\"\n%cd $PROJECT_DIR"),
    nbf.v4.new_code_cell("#@title 4. Install dependencies\n!apt-get update -qq\n!apt-get install -y -qq redis-server postgresql libgl1\n!python -m pip install -U pip setuptools wheel\n!python -m pip install -r backend/requirements.txt\n!python -m pip install -r models/requirements.txt\n!python -m pip install pytest qdrant-client pyngrok nest_asyncio"),
    nbf.v4.new_code_cell("#@title 5. Load Trained Weights from Drive\nimport shutil\nfrom pathlib import Path\n\nif USE_DRIVE:\n    src_dir = Path(DRIVE_WEIGHTS_DIR)\n    dst_dir = Path(PROJECT_DIR) / \"models/weights\"\n    dst_dir.mkdir(parents=True, exist_ok=True)\n    for p in src_dir.glob(\"*.pt\"):\n        print(f\"Copying {p.name}...\")\n        shutil.copy2(p, dst_dir / p.name)\n    print(\"Weights loaded!\")"),
    nbf.v4.new_code_cell("#@title 6. Start Infrastructure Services\n!service redis-server start\n!service postgresql start\n!sudo -u postgres psql -c \"CREATE USER medscope WITH PASSWORD 'password';\"\n!sudo -u postgres psql -c \"CREATE DATABASE medscope_db OWNER medscope;\"\n\n!wget -q https://github.com/qdrant/qdrant/releases/download/v1.7.0/qdrant-x86_64-unknown-linux-gnu.tar.gz\n!tar -xzf qdrant-x86_64-unknown-linux-gnu.tar.gz\nimport subprocess, time\nsubprocess.Popen([\"./qdrant\"])\ntime.sleep(3)"),
    nbf.v4.new_code_cell("#@title 7. Run Backend API via ngrok\nimport nest_asyncio\nfrom pyngrok import ngrok\nimport uvicorn\nimport os\nfrom backend.main import app\n\nif not NGROK_AUTH_TOKEN:\n    raise ValueError(\"Please provide an NGROK_AUTH_TOKEN in step 1\")\n\nngrok.set_auth_token(NGROK_AUTH_TOKEN)\npublic_url = ngrok.connect(8000)\nprint(f\"\\n\\n>>> API is available at: {public_url.public_url} <<<\\n\\n\")\n\nos.environ['YOLO_WEIGHTS_PATH'] = str(Path(PROJECT_DIR) / \"models/weights/yolov11_malaria_best.pt\")\n\nnest_asyncio.apply()\nuvicorn.run(app, host=\"0.0.0.0\", port=8000)")
]
nbf.write(nb, "notebooks/MedScope_AI_Colab_Inference.ipynb")
