'use client';

import Link from 'next/link';

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-background text-foreground relative overflow-hidden">
      {/* Dynamic Background Gradients */}
      <div className="fixed top-[-10%] left-[-10%] w-[40%] h-[40%] bg-[#06b6d4]/10 blur-[120px] rounded-full pointer-events-none"></div>
      <div className="fixed bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-pink-400/10 blur-[120px] rounded-full pointer-events-none"></div>

      {/* Back to Home Button */}
      <Link href="/" className="fixed top-8 left-8 z-[200] flex items-center gap-2 px-5 py-2.5 rounded-full border-2 border-foreground bg-background text-foreground font-medium shadow-[3px_3px_0px_theme(colors.foreground)] hover:-translate-y-0.5 hover:shadow-[5px_5px_0px_theme(colors.foreground)] active:translate-y-1 active:translate-x-1 active:shadow-[0px_0px_0px_theme(colors.foreground)] transition-all">
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="m15 18-6-6 6-6"/></svg>
        Back to Home
      </Link>

      <div className="max-w-6xl mx-auto px-6 pt-32 pb-24 relative z-10">
        <header className="mb-16">
          <h1 className="text-5xl lg:text-7xl font-heading font-extrabold tracking-tight mb-4">
            Terms of Service
          </h1>
          <p className="text-xl font-sans text-foreground/60 font-medium">
            Last Updated: {new Date().toLocaleDateString()}
          </p>
        </header>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-start">
          
          {/* Sticky Table of Contents Sidebar */}
          <aside className="lg:col-span-4 sticky top-12 hidden md:block">
            <div className="p-8 rounded-3xl bg-background border-2 border-foreground shadow-[6px_6px_0px_theme(colors.foreground)]">
              <h3 className="font-heading font-bold text-2xl mb-6">Contents</h3>
              <nav className="flex flex-col gap-3 font-sans font-medium text-foreground/70">
                <a href="#acceptance" className="hover:text-foreground hover:translate-x-1 transition-all">1. Acceptance of Terms</a>
                <a href="#disclaimer" className="hover:text-foreground hover:translate-x-1 transition-all">2. Clinical Disclaimer</a>
                <a href="#data-ip" className="hover:text-foreground hover:translate-x-1 transition-all">3. Data & Intellectual Property</a>
                <a href="#liability" className="hover:text-foreground hover:translate-x-1 transition-all">4. Limitation of Liability</a>
              </nav>
            </div>
          </aside>

          {/* Long-form Content Column */}
          <article className="lg:col-span-8 font-sans text-lg text-foreground/80 leading-loose space-y-12">
            
            <section id="acceptance" className="scroll-mt-32">
              <h2 className="text-3xl font-heading font-bold text-foreground mb-6">1. Acceptance of Terms</h2>
              <p className="mb-4">
                Welcome to MedScope AI. By registering an account and using our clinical decision support pipeline, you agree to be bound by these Terms of Service. If you do not agree to all of these terms, you may not access or use our services.
              </p>
              <p className="mb-4">
                We make a distinction between Academic/Research use (which may be provided free of charge under a specific license) and Enterprise Clinical use (which requires a paid subscription agreement). Misuse of academic access for commercial clinical throughput will result in immediate termination of the account.
              </p>
            </section>

            <section id="disclaimer" className="scroll-mt-32">
              <h2 className="text-3xl font-heading font-bold text-foreground mb-6">2. Clinical & Medical Disclaimer</h2>
              <div className="p-6 border-l-4 border-[#06b6d4] bg-background/50 rounded-r-2xl mb-6">
                <strong className="text-foreground text-xl block mb-2 font-heading">Not Medical Advice</strong>
                <p>MedScope AI provides artificial intelligence-assisted image analysis and explainability maps (such as Grad-CAM and SHAP values). It is <em>strictly</em> a decision-support tool and does not provide definitive medical diagnoses.</p>
              </div>
              <p className="mb-4">
                All results generated by MedScope AI must be reviewed, interpreted, and verified by a licensed pathologist or certified medical professional. You acknowledge that we are not liable for misdiagnoses, medical errors, or adverse outcomes resulting from the over-reliance on our AI models without proper human clinical oversight.
              </p>
            </section>

            <section id="data-ip" className="scroll-mt-32">
              <h2 className="text-3xl font-heading font-bold text-foreground mb-6">3. Data Usage & Intellectual Property</h2>
              <p className="mb-4">
                <strong>Your Data:</strong> You retain full ownership and intellectual property rights to the slide images and raw data you upload to the platform.
              </p>
              <p className="mb-4">
                <strong>Model Training:</strong> For free and academic users, anonymized subsets of your data may be utilized to further train, benchmark, and improve our underlying detection models. Enterprise users operate under strict data isolation guarantees and their clinical data is never used to train global models.
              </p>
            </section>

            <section id="liability" className="scroll-mt-32">
              <h2 className="text-3xl font-heading font-bold text-foreground mb-6">4. Limitation of Liability</h2>
              <p className="mb-4">
                To the maximum extent permitted by applicable law, MedScope AI and its affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly.
              </p>
              <p>
                We do not warrant that our services will be uninterrupted, error-free, or completely secure. Your use of the service is at your sole risk.
              </p>
            </section>

          </article>
        </div>
      </div>
    </div>
  );
}
